image: alpine:3.12

variables:
    DOCKER_DRIVER: overlay

test build:
  stage: build
  tags:
    - docker
    - shared
  script:
    - apk --update add python3 py3-pip gcc python3-dev musl-dev libffi libffi-dev openssl-dev openssl
    - pip3 install ansible
    - ansible-galaxy collection build