namespace: "markuman"
name: "nextcloud"
version: "0.1.0"
readme: "README.md"
authors:
    - "Markus Bergholz <markuman+spambelongstogoogle@gmail.com>"
license:
    - "GPL-3.0-or-later"
tags:
    - nextcloud
    - collection
repository: "https://git.osuv.de/m/nextcloud_collection"